# Generated by Django 3.2.4 on 2021-06-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_catagory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
