# Generated by Django 3.2.4 on 2021-06-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_items_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
