# Generated by Django 3.2.4 on 2021-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'New Product'), ('hot', 'Hot Product'), ('sale', 'Sale Product')], max_length=100),
        ),
    ]
