# Generated by Django 3.2.4 on 2021-06-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210603_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discountedprice',
            new_name='discounted_price',
        ),
    ]
